"""Added date to possible ValueType

Revision ID: 00689ba62afa
Revises: 97e10106ecf4
Create Date: 2024-01-18 15:38:27.510744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00689ba62afa'
down_revision: Union[str, None] = '97e10106ecf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_date', sa.Date(), nullable=True))
        
    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_text', sa.Text(), nullable=True))
        
    with op.batch_alter_table('other_types', schema=None) as batch_op:
        batch_op.alter_column('value_type', type_=sa.Enum('str', 'int', 'float', 'bool', 'date', 'text', name='value_type', create_constraint=True), nullable=False)

    with op.batch_alter_table('sample_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_date', sa.Date(), nullable=True))
        
    with op.batch_alter_table('sample_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_text', sa.Text(), nullable=True))
        
    with op.batch_alter_table('sample_detail_types', schema=None) as batch_op:
        batch_op.alter_column('value_type', type_=sa.Enum('str', 'int', 'float', 'bool', 'date', 'text', name='value_type', create_constraint=True), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_details', schema=None) as batch_op:
        batch_op.drop_column('value_date')
        
    with op.batch_alter_table('sample_details', schema=None) as batch_op:
        batch_op.drop_column('value_text')
        
    with op.batch_alter_table('other_types', schema=None) as batch_op:
        batch_op.alter_column('value_type', type_=sa.Enum('str', 'int', 'float', 'bool', name='value_type', create_constraint=True), nullable=False)

    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.drop_column('value_date')
        
    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.drop_column('value_text')
        
    with op.batch_alter_table('sample_detail_types', schema=None) as batch_op:
        batch_op.alter_column('value_type', type_=sa.Enum('str', 'int', 'float', 'bool', name='value_type', create_constraint=True), nullable=False)

    # ### end Alembic commands ###
